### ISSUE TITLE
Merge cl-cookbook into lisp-lang

### ISSUE THREAD

**Issue by can3p** [LispLang/lisplang.github.io#38]
Hi!

There was an effort to rejuvenate cl-cookbook project on github - https://github.com/LispCookbook/cl-cookbook

I think this content is still valuable and it would be nice to have it as part of lisp-lang.org.
I can give it a try to make it as part of the wiki. What do you think?

**Comment by eudoxia0** [comment]
The thing about the cookbook is, after moving it to GitHub and Jekyll and fixing some things, I don't think the content has been updated much. For instance, the chapter about the OS interface has tons of implementation-specific code, as opposed to calling a library like OSICAT; the FFI chapter uses Allegro specific FFI code rather than the (already quite well established) CFFI; and the sockets chapter uses PORT, a library from the CLOCC, rather than the more widely used usocket.

So, yeah. Outside of things like, say, strings, I don't see much value in moving the cookbook here.
